default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  
development:
  <<: *default
  host: localhost
  database: dresscode_dev

test:
  <<: *default
  database: dresscode_test

production:
  <<: *default
  database: drescoode
