development:
  adapter: postgresql
  encoding: unicode
  database: dresscode_development
  pool: 5
  username: BernzAir
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: dresscode_test
  pool: 5
  username: BernzAir
  password:
