# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6d9f36faf52c7e71189ef07e7121ce6b31a7bb135b66c39b6e9edbfe7ed26d5072c7cbf90b15fa4925e4d6a46b336a2e305befc0b558d69c1bcfb346917d1f6e

test:
  secret_key_base: 405c8cd31691cd575af4bd526880c4b02733b34e6cf2db4c7637f2872228aaeec6deda061cfd265806fc0fffea091daed7592076dfa28149397ef5c81f054df6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
